# Generated by Django 5.2.7 on 2025-10-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(default='USD', max_length=3)),
                ('target', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('base', 'target', 'date')},
            },
        ),
    ]
